import { z } from "zod";
import { MAX_PATCH_OPERATIONS, MAX_FREEHAND_POINTS } from "../contract";

const generationPointSchema = z.strictObject({
  x: z.number().int().min(0).max(1000),
  y: z.number().int().min(0).max(1000),
});

const generationBoxSchema = z.strictObject({
  x: z.number().int().min(0).max(1000),
  y: z.number().int().min(0).max(1000),
  width: z.number().int().min(10).max(1000),
  height: z.number().int().min(10).max(1000),
});

const generationStyleSchema = z.strictObject({
  theme: z.enum(["ink", "muted", "accent", "info", "success", "warning", "danger"]).nullable(),
  fill: z.enum(["transparent", "solid", "hachure"]).nullable(),
  stroke: z.enum(["solid", "dashed", "dotted"]).nullable(),
  weight: z.enum(["thin", "regular", "bold"]).nullable(),
  opacity: z.number().int().min(20).max(100).nullable(),
});

const generationElementSchema = z.strictObject({
  kind: z.enum(["note", "rectangle", "ellipse", "text", "frame", "arrow", "freehand"]),
  box: generationBoxSchema.nullable(),
  text: z.string().trim().min(1).max(500).nullable(),
  label: z.string().trim().min(1).max(160).nullable(),
  points: z.array(generationPointSchema).min(2).max(MAX_FREEHAND_POINTS).nullable(),
  style: generationStyleSchema.nullable(),
});

// OpenAI strict structured outputs do not accept the oneOf generated by Zod
// discriminated unions. This provider-facing superset keeps every field required
// and nullable; nulls are pruned and the canonical CanvasPatch schema performs
// the final operation-specific validation before a patch can leave the server.
export const canvasPatchGenerationSchema = z.strictObject({
  version: z.literal("1"),
  baseSceneVersion: z.string().trim().min(1).max(128),
  summary: z.string().trim().min(1).max(300),
  operations: z.array(z.strictObject({
    op: z.enum(["create", "update", "move", "group", "connect", "delete"]),
    ref: z.string().nullable(),
    target: z.string().nullable(),
    groupRef: z.string().nullable(),
    members: z.array(z.string()).nullable(),
    from: z.string().nullable(),
    to: generationPointSchema.nullable(),
    connectionTo: z.string().nullable(),
    label: z.string().trim().min(1).max(160).nullable(),
    reason: z.string().trim().min(1).max(240).nullable(),
    text: z.string().trim().min(1).max(500).nullable(),
    style: generationStyleSchema.nullable(),
    element: generationElementSchema.nullable(),
  })).min(1).max(MAX_PATCH_OPERATIONS),
});
