'use client'

import { useState } from 'react'
import {
  ProjectPageShell,
  ProjectHero,
  ProjectSection,
  ProjectMedia,
  ProjectBulletList,
  ProjectTagList,
  ProjectStatGrid,
} from '@/components/project-detail'
import { getProjectBySlug } from '@/data/projects'

export default function FlowStatePage() {
  const [activeItem, setActiveItem] = useState('#overview')
  const project = getProjectBySlug('flowstate')

  if (!project) {
    return <div>Project not found</div>
  }

  const navigation = [
    { name: 'Overview', href: '#overview' },
    { name: 'Approach', href: '#approach' },
    { name: 'Stack', href: '#stack' },
    { name: 'Experience', href: '#experience' },
    { name: 'Impact', href: '#impact' },
  ]

  return (
    <ProjectPageShell
      project={project}
      navigation={navigation}
      activeItem={activeItem}
      onItemClick={setActiveItem}
    >
      <ProjectHero
        eyebrow="AI productivity"
        title="FlowState"
        description="An AI-guided productivity system that turns chaotic student schedules into focused, structured work blocks with a calm interface and an agent-driven planning layer."
        accentColor={project.primaryColor}
        actions={project.githubUrl ? [{ label: 'View source', href: project.githubUrl }] : []}
      />

      <ProjectSection
        id="overview"
        eyebrow="Overview"
        title="Designed for deep work"
        subtitle="A clean interface and automated planning system that keep students on track."
      >
        <div className="grid gap-8 lg:grid-cols-2">
          <div className="space-y-4 text-sm text-slate-600 sm:text-base">
            <p>
              Students constantly context-switch between an LMS, calendars, chat, and ad-hoc notes.
              FlowState consolidates assignments, priorities, and schedules into a single plan.
            </p>
            <p>
              A LangGraph-style orchestration layer coordinates specialized agents for scheduling,
              insights, and contextual recommendations so planning stays automatic.
            </p>
          </div>
          <ProjectMedia
            src="/images/FSAnimation.mov"
            alt="FlowState overview animation"
            type="video"
          />
        </div>
      </ProjectSection>

      <ProjectSection
        id="approach"
        eyebrow="Approach"
        title="AI-first workflow"
        subtitle="Key capabilities that make the platform feel supportive, not noisy."
      >
        <ProjectBulletList
          items={[
            'Real-time assistant with streaming responses and clear progress feedback.',
            'Unified academic hub for assignments, course context, and priorities.',
            'Adaptive scheduling that adjusts to workload and focus patterns.',
            'Dynamic content when helpful (small interactive UI snippets instead of walls of text).',
            'Lightweight analytics: overload warnings and productivity patterns without nagging.',
          ]}
        />
      </ProjectSection>

      <ProjectSection
        id="stack"
        eyebrow="Stack"
        title="Technology"
        subtitle="The core tools that power the product."
      >
        <div className="space-y-4">
          <p className="text-sm text-slate-600 sm:text-base">
            Frontend focuses on speed and clarity; the backend/AI layer focuses on orchestration and streaming.
          </p>
          <ProjectTagList items={project.technologies} />
        </div>
      </ProjectSection>

      <ProjectSection
        id="experience"
        eyebrow="Experience"
        title="Focused interaction design"
        subtitle="Minimal surfaces with just the right amount of feedback."
      >
        <div className="grid gap-8 lg:grid-cols-2">
          <ProjectMedia
            src="/images/flowstateChat.mp4"
            alt="FlowState chat interface"
            type="video"
          />
          <ProjectBulletList
            items={[
              'Calm typography and restrained color to keep long sessions comfortable.',
              'Clear loading/progress states so the system never feels vague.',
              'Mobile-first layouts for quick replans between classes.',
            ]}
          />
        </div>
      </ProjectSection>

      <ProjectSection
        id="impact"
        eyebrow="Impact"
        title="Outcome"
        subtitle="A platform built for sustained attention, not constant alerts."
      >
        <ProjectStatGrid
          items={[
            { label: 'Planning', value: 'Automated', description: 'Schedules and reminders are generated by the system.' },
            { label: 'Focus', value: 'Sustained', description: 'Clear task context reduces cognitive switching.' },
            { label: 'AI Layer', value: 'Orchestrated', description: 'Specialized agents handle distinct student needs.' },
            { label: 'UX', value: 'Quiet', description: 'A calmer interface keeps attention on the work.' },
          ]}
        />
      </ProjectSection>
    </ProjectPageShell>
  )
}
