'use client'

import { useState } from 'react'
import {
  ProjectPageShell,
  ProjectHero,
  ProjectSection,
  ProjectMedia,
  ProjectBulletList,
  ProjectTagList,
  ProjectStatGrid,
} from '@/components/project-detail'
import { getProjectBySlug } from '@/data/projects'

export default function FlowStatePage() {
  const [activeItem, setActiveItem] = useState('#overview')
  const project = getProjectBySlug('flowstate')

  if (!project) {
    return <div>Project not found</div>
  }

  const navigation = [
    { name: 'Overview', href: '#overview' },
    { name: 'Approach', href: '#approach' },
    { name: 'Stack', href: '#stack' },
    { name: 'Experience', href: '#experience' },
    { name: 'Impact', href: '#impact' },
  ]

  return (
    <ProjectPageShell
      project={project}
      navigation={navigation}
      activeItem={activeItem}
      onItemClick={setActiveItem}
    >
      <ProjectHero
        eyebrow="AI productivity"
        title="FlowState"
        description="An AI-guided productivity system that turns chaotic student schedules into focused, structured work blocks."
        accentColor={project.primaryColor}
        actions={project.githubUrl ? [{ label: 'View source', href: project.githubUrl }] : []}
      />

      <ProjectSection
        id="overview"
        eyebrow="Overview"
        title="Designed for deep work"
        subtitle="A clean interface and automated planning system that keep students on track."
      >
        <div className="grid gap-8 lg:grid-cols-2">
          <div className="space-y-4 text-sm text-slate-600 sm:text-base">
            <p>
              FlowState combines AI orchestration with a calm UI to help students prioritize tasks,
              manage due dates, and stay in flow. The system handles the heavy planning so the user can focus.
            </p>
            <p>
              A dedicated agent layer powers scheduling, intelligent insights, and contextual recommendations.
            </p>
          </div>
          <ProjectMedia
            src="/images/FSAnimation.mov"
            alt="FlowState overview animation"
            type="video"
          />
        </div>
      </ProjectSection>

      <ProjectSection
        id="approach"
        eyebrow="Approach"
        title="AI-first workflow"
        subtitle="Key capabilities that make the platform feel supportive, not noisy."
      >
        <ProjectBulletList
          items={[
            'Real-time AI assistant for questions, summaries, and next-step suggestions.',
            'Unified academic hub that keeps assignments, course content, and priorities in one view.',
            'Adaptive scheduling that adjusts to workload and focus patterns.',
          ]}
        />
      </ProjectSection>

      <ProjectSection
        id="stack"
        eyebrow="Stack"
        title="Technology"
        subtitle="The core tools that power the product." 
      >
        <ProjectTagList items={project.technologies} />
      </ProjectSection>

      <ProjectSection
        id="experience"
        eyebrow="Experience"
        title="Focused interaction design"
        subtitle="Minimal surfaces with just the right amount of feedback."
      >
        <ProjectMedia
          src="/images/flowstateChat.mp4"
          alt="FlowState chat interface"
          type="video"
        />
      </ProjectSection>

      <ProjectSection
        id="impact"
        eyebrow="Impact"
        title="Outcome"
        subtitle="A platform built for sustained attention, not constant alerts."
      >
        <ProjectStatGrid
          items={[
            { label: 'Planning', value: 'Automated', description: 'Schedules and reminders are generated by the system.' },
            { label: 'Focus', value: 'Sustained', description: 'Clear task context reduces cognitive switching.' },
            { label: 'AI Layer', value: 'Orchestrated', description: 'Specialized agents handle distinct student needs.' },
            { label: 'UX', value: 'Quiet', description: 'Design choices emphasize calm and readability.' },
          ]}
        />
      </ProjectSection>
    </ProjectPageShell>
  )
}
