"use client";

import { useState } from "react";
import {
  ProjectPageShell,
  ProjectHero,
  ProjectSection,
  ProjectMedia,
  ProjectBulletList,
  ProjectTagList,
  ProjectStatGrid,
} from "@/components/project-detail";
import { getProjectBySlug } from "@/data/projects";

export default function JobPersonalizerPage() {
  const [activeItem, setActiveItem] = useState("#overview");
  const project = getProjectBySlug("job-personalizer");

  if (!project) {
    return <div>Project not found</div>;
  }

  const navigation = [
    { name: "Overview", href: "#overview" },
    { name: "Workflow", href: "#workflow" },
    { name: "Stack", href: "#stack" },
    { name: "Impact", href: "#impact" },
    { name: "Proof", href: "#proof" },
  ];

  return (
    <ProjectPageShell
      project={project}
      navigation={navigation}
      activeItem={activeItem}
      onItemClick={setActiveItem}
    >
      <ProjectHero
        eyebrow="Automation"
        title="Resume Personalization"
        description="An n8n workflow that pulls new roles, customizes resumes with dual LLMs, and routes approvals through email before submission."
        accentColor={project.primaryColor}
        actions={project.githubUrl ? [{ label: "View source", href: project.githubUrl }] : []}
      />

      <ProjectSection
        id="overview"
        eyebrow="Overview"
        title="From job discovery to delivery"
        subtitle="A two-part workflow that keeps job hunting consistent and fast."
      >
        <div className="grid gap-8 lg:grid-cols-2">
          <div className="space-y-4 text-sm text-slate-600 sm:text-base">
            <p>
              The system watches a curated job feed, filters new listings, and routes the best options into a
              Notion database and Slack for quick selection.
            </p>
            <p>
              Once a role is selected, the workflow scrapes the posting, extracts relevant skills, and generates
              a tailored resume with a human-in-the-loop approval step.
            </p>
          </div>
          <ProjectMedia
            src="/images/slackn8nsuperthingy.png"
            alt="n8n workflow overview"
            caption="Job intake, filtering, and Slack routing in one automated flow."
          />
        </div>
      </ProjectSection>

      <ProjectSection
        id="workflow"
        eyebrow="Workflow"
        title="Concise automation loop"
        subtitle="Each step is designed to minimize manual effort."
      >
        <ProjectBulletList
          items={[
            "Scheduled pulls from internship repositories every few hours.",
            "Slack-based selection to choose which roles move forward.",
            "Dual-LLM pass to extract skills and tailor the Typst resume.",
            "Gmail approval flow to keep quality high before submission.",
          ]}
        />
      </ProjectSection>

      <ProjectSection
        id="stack"
        eyebrow="Stack"
        title="Technology"
        subtitle="Core tooling across the workflow."
      >
        <ProjectTagList items={project.technologies} />
      </ProjectSection>

      <ProjectSection
        id="impact"
        eyebrow="Impact"
        title="Outcome"
        subtitle="Automates the tedious parts while keeping review control." 
      >
        <ProjectStatGrid
          items={[
            { label: "Time saved", value: "Hours", description: "Reduces manual search and resume edits." },
            { label: "Quality", value: "Checked", description: "Human approval keeps the output reliable." },
            { label: "Tracking", value: "Centralized", description: "All jobs live in a single Notion view." },
            { label: "Iteration", value: "Fast", description: "Feedback loops into the next resume draft." },
          ]}
        />
      </ProjectSection>

      <ProjectSection
        id="proof"
        eyebrow="Proof"
        title="Generated output"
        subtitle="A sample of the resume generated by the workflow."
      >
        <ProjectMedia
          src="/images/NEWRESUME.png"
          alt="Generated resume sample"
        />
      </ProjectSection>
    </ProjectPageShell>
  );
}
